# Changes here will be overwritten by Copier
_commit: v0.3.0-beta-10-g7a69bf4
_src_path: https://github.com/VOLTTRON/copier-poetry-volttron-agent.git
author_email: volttron@pnnl.gov
author_fullname: Mark Bonicillo
author_username: VOLTTRON
copyright_date: '2022'
copyright_holder: Volttron
copyright_holder_email: volttron@pnnl.gov
copyright_license: Apache License 2.0
project_description: The Actuator Agent is used to manage write access to devices. Other agents may request scheduled times, called Tasks, to interact with one or more devices.
project_name: volttron-actuator
python_agent_class_name: ActuatorAgent
python_package_command_line_name: volttron-actuator
python_package_distribution_name: volttron-actuator
python_package_import_name: volttron_actuator
repository_name: volttron-actuator
repository_namespace: VOLTTRON
repository_provider: github.com
use_precommit: true
